import type { Metadata } from 'next'
// `pages/_app.js`
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className='bg-slate-800'>{children}</body>
    </html>
  )
}
